M48
; DRILL file {KiCad 9.0.4} date 2026-03-07T22:54:10-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-07T22:54:10-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,Plated,1,4,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.800
%
G90
G05
T1
X119.0Y-37.7
X120.95Y-37.7
T2
X116.8Y-43.0
X118.8Y-43.0
X120.8Y-43.0
X122.8Y-43.0
M30
